version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Building the React app...
      - echo Checking Node.js version...
      - node --version
      - npm --version
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://static-web-bucket-01020304 --delete